### ISSUE TITLE
中文内容粘贴到emacs里面变乱码，咋整？

### ISSUE THREAD

**Issue by ocde** [ocde/ego#13]
自己解决，自己顶。 

将 .emacs 中的 
(set-clipboard-coding-system 'utf-8) 
改为 
(set-clipboard-coding-system 'euc-cn) 
之后，就没有问题了。 

看起来在windows中的剪贴板中的中文内容不是以utf-8形式存放的。 

【 在 melodies (明天就做窝) 的大作中提到: 】 
: 中文，win7, 
: GNU Emacs 24.0.50.1 (i386-mingw-nt6.1.7601) 
:  of 2010-11-10 on SHAN-PC 
: ................... 

正解也。

**Comment by yyj603** [comment]
太好了,谢谢指点
