### ISSUE TITLE
osclass 如何支持中文搜索（折中解决方案）

### ISSUE THREAD

**Issue by ocde** [ocde/ego#30]
https://github.com/osclass/Osclass/issues/1221

http://forums.osclass.org/general-help/how-to-search-in-east-asian-characters/

There's a solution:modify this line https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/model/Search.php#L800

to something like

$this->dao->where(sprintf("(d.s_title LIKE '%%%s%%' OR d.s_description LIKE '%%%s%%')", $this->sPattern, $this->sPattern));

**Comment by atbad** [comment]
看不懂要怎么实现
